# GoReleaser configuration for CLIProxyAPI
# This configuration builds the frontend before compiling the Go binary

before:
  hooks:
    # Ensure go.mod is tidy
    - go mod tidy
    # Build frontend (requires Node.js and npm in the build environment)
    - bash -c "cd web && npm ci && npm run build"

builds:
  - id: "cli-proxy-api"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/server/
    binary: cli-proxy-api
    ldflags:
      - -s -w -X 'main.Version={{.Version}}' -X 'main.Commit={{.ShortCommit}}' -X 'main.BuildDate={{.Date}}'

archives:
  - id: "cli-proxy-api"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - README_CN.md
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
