package managementasset

import (
	_ "embed"
)

// EmbeddedManagementHTML contains the embedded management control panel HTML.
// This file is generated by building the frontend project (web/).
// If the file doesn't exist during compilation, the embed will be empty.
//
//go:embed management.html
var EmbeddedManagementHTML []byte

// HasEmbeddedHTML returns true if the embedded HTML is available and non-empty.
func HasEmbeddedHTML() bool {
	return len(EmbeddedManagementHTML) > 0
}
